2996513 scope lock fix
dennisinteractive/js_manager pull request #1
Opened 2018-08-31 15:03 UTC by jimwills123

2018-08-31 22:25 UTC, davidgrayston requested changes
Few very minor things, but otherwise looks like a good solution to prevent advagg moving head scripts to footer

2018-08-31 22:25 UTC, davidgrayston commented on js_manager.install
> +function js_manager_schema_alter() {
Is it necessary to alter the schema provided by this module?

2018-08-31 22:25 UTC, davidgrayston commented on js_manager.install
> +  db_add_field('js_manager_add_js', 'scope_lock', $schema['fields']['scope_lock']);
Inconsistent indentation

2018-09-03 09:38 UTC, jimwills123 commented on js_manager.install
> +function js_manager_schema_alter() {
done

2018-09-03 09:39 UTC, jimwills123 commented on js_manager.install
> +  db_add_field('js_manager_add_js', 'scope_lock', $schema['fields']['scope_lock']);
done

2018-09-03 14:35 UTC, jon-edery approved these changes

2018-09-05 08:48 UTC, merged